language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
  - markdown_files=$(ls -m *.md); awesome_bot --files ${markdown_files//, /,} --allow-redirect --allow-ssl

notifications:
  email: false